baseURL = "https://blog.davemartin.me/"
languageCode = "en-gb"
title = "Dave Martin's Blog"
theme = "vienna"

[Params]
  twitter = "DWMartin41"
  github = "DaveWM"
  linkedin = "davewm"
  themecolor = "#1B3B6F"
  contact = "mailto:mail@davemartin.me"
  subtitle = "A blog about functional web development"
  author = "Dave Martin"
  bio = "Functional Web Developer"
  avatar = "/images/profile-small.jpg"
  description = "A blog about front-end and back-end functional programming"
  portfolio = "https://davemartin.me"