baseURL = "https://blog.davemartin.me/"
languageCode = "en-gb"
title = "Dave Martin's Blog"
theme = "vienna"

[Params]
  github = "DaveWM"
  linkedin = "davewm"
  themecolor = "#1B3B6F"
  contact = "mailto:mail@davemartin.me"
  subtitle = "A blog about functional software development"
  author = "Dave Martin"
  bio = "Functional Software Developer"
  avatar = "/images/profile-small.jpg"
  description = "A blog about front-end and back-end functional programming"
  portfolio = "https://davemartin.me"

[markup]
  [markup.blackFriday]
    hrefTargetBlank = true
  [markup.highlight]
    noClasses = true
    codeFences = false
    noHl = true
    style = ''
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
